apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nestor-orchestrator.fullname" . }}-config
  labels:
    {{- include "nestor-orchestrator.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      host: {{ .Values.config.server.host | quote }}
      port: {{ .Values.config.server.port }}
      read_timeout: {{ .Values.config.server.readTimeout | quote }}
      write_timeout: {{ .Values.config.server.writeTimeout | quote }}
      shutdown_timeout: {{ .Values.config.server.shutdownTimeout | quote }}

    logging:
      level: {{ .Values.config.logging.level | quote }}
      format: {{ .Values.config.logging.format | quote }}
      enable_structured: {{ .Values.config.logging.enableStructured }}

    storage:
      type: {{ .Values.config.storage.type | quote }}
      {{- if eq .Values.config.storage.type "dynamodb" }}
      dynamodb:
        table_name: {{ .Values.config.storage.dynamodb.tableName | quote }}
        region: {{ .Values.config.storage.dynamodb.region | quote }}
        {{- if .Values.config.storage.dynamodb.endpoint }}
        endpoint: {{ .Values.config.storage.dynamodb.endpoint | quote }}
        {{- end }}
        read_capacity: {{ .Values.config.storage.dynamodb.readCapacity }}
        write_capacity: {{ .Values.config.storage.dynamodb.writeCapacity }}
        enable_point_in_time_recovery: {{ .Values.config.storage.dynamodb.enablePointInTimeRecovery }}
      {{- end }}

    cache:
      type: {{ .Values.config.cache.type | quote }}
      {{- if eq .Values.config.cache.type "redis" }}
      redis:
        url: {{ .Values.config.cache.redis.url | quote }}
        pool_size: {{ .Values.config.cache.redis.poolSize }}
        max_retries: {{ .Values.config.cache.redis.maxRetries }}
        ttl: {{ .Values.config.cache.redis.ttl | quote }}
      {{- end }}

    git:
      repositories:
        {{- range .Values.config.git.repositories }}
        - name: {{ .name | quote }}
          url: {{ .url | quote }}
          path: {{ .path | quote }}
          branch: {{ .branch | quote }}
          poll_interval: {{ .pollInterval | quote }}
        {{- end }}

    sse:
      enabled: {{ .Values.config.sse.enabled }}
      max_connections: {{ .Values.config.sse.maxConnections }}
      heartbeat_interval: {{ .Values.config.sse.heartbeatInterval | quote }}
      buffer_size: {{ .Values.config.sse.bufferSize }}

    metrics:
      enabled: {{ .Values.config.metrics.enabled }}
      path: {{ .Values.config.metrics.path | quote }}
      port: {{ .Values.config.metrics.port }}

    validation:
      cache_enabled: {{ .Values.config.validation.cacheEnabled }}
      cache_ttl: {{ .Values.config.validation.cacheTTL | quote }}
      cache_size: {{ .Values.config.validation.cacheSize }}
