{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nestor-orchestrator.fullname" . }}
  labels:
    {{- include "nestor-orchestrator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nestor-orchestrator.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- with .Values.networkPolicy.policyTypes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
