apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "nestor-orchestrator.fullname" . }}-test-connection"
  labels:
    {{- include "nestor-orchestrator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:latest
      command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Testing orchestrator health endpoint..."
          curl -f http://{{ include "nestor-orchestrator.fullname" . }}:{{ .Values.service.port }}/health

          echo "Testing orchestrator ready endpoint..."
          curl -f http://{{ include "nestor-orchestrator.fullname" . }}:{{ .Values.service.port }}/ready

          echo "Testing metrics endpoint..."
          curl -f http://{{ include "nestor-orchestrator.fullname" . }}:{{ .Values.service.port }}/metrics

          echo "All tests passed!"
