version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/cli"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/orchestrator"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/processor"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/shared"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker
  - package-ecosystem: "docker"
    directory: "/orchestrator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/processor"
    schedule:
      interval: "weekly"

  # Documentation dependencies
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
