name: Release Orchestrator

on:
  push:
    tags:
      - "orchestrator/v*"

permissions:
  contents: write
  packages: write

jobs:
  release-orchestrator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          tag=${GITHUB_REF#refs/tags/orchestrator/}
          echo "version=${tag}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.work

      - name: Go work sync
        run: go work sync

      - name: Run tests
        run: |
          cd orchestrator
          go test -v ./...

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: orchestrator/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/orchestrator:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}/orchestrator:latest
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
            COMPONENT=orchestrator

      - name: Build binaries
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: orchestrator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORCHESTRATOR_VERSION: ${{ steps.version.outputs.version }}

      - name: Update Helm chart
        run: |
          # Update Helm chart version in deployments/helm/nestor-orchestrator/Chart.yaml
          sed -i "s/version: .*/version: ${VERSION#v}/" deployments/helm/nestor-orchestrator/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: ${VERSION}/" deployments/helm/nestor-orchestrator/Chart.yaml
        env:
          VERSION: ${{ steps.version.outputs.version }}
